---

- name: get list of projects
  k8s_info:
    api_version: project.openshift.io/v1
    kind: Project
    validate_certs: "{{ lookup('env','K8S_AUTH_VERIFY_SSL') | bool }}"
  register: project_list
  failed_when: false

- name: set cluster to kubernetes
  set_fact:
    cluster: kubernetes
  when: project_list.api_found is undefined or not project_list.api_found